{
 "title": "Debug Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"sis\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r[\"_measurement\"] ==\"gateway_debugging\")\n  |> filter(fn: (r) => r[\"_field\"]==\"temperature\")\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "type": "timeseries"
    }
   ]
  },
  {
   "title": "Bus Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"sis\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r[\"_measurement\"] ==\"gateway_debugging\")\n  |> filter(fn: (r) => r[\"_field\"]==\"bus_voltage\")\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "type": "timeseries"
    }
   ]
  },
  {
   "title": "Shunt Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"sis\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r[\"_measurement\"] ==\"gateway_debugging\")\n  |> filter(fn: (r) => r[\"_field\"]==\"shunt_voltage\")\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "type": "timeseries"
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"sis\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r[\"_measurement\"] ==\"gateway_debugging\")\n  |> filter(fn: (r) => r[\"_field\"]==\"current\")\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "type": "timeseries"
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"sis\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r[\"_measurement\"] ==\"gateway_debugging\")\n  |> filter(fn: (r) => r[\"_field\"]==\"power\")\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "type": "timeseries"
    }
   ]
  },
  {
   "title": "p",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"sis\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r[\"_measurement\"] ==\"gateway_debugging\")\n  |> filter(fn: (r) => r[\"_field\"]==\"p\")\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "type": "timeseries"
    }
   ]
  }
 ]
}