{
 "title": "Weather Station Dashboard",
 "panels": [
  {
   "title": "Weather Station Location",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"sis\")\n  |> range(start: -10y)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"device_registration\")\n  |> filter(fn: (r) => r[\"_field\"] == \"longitude\" or r[\"_field\"] == \"latitude\")\n  |> filter(fn: (r) => r[\"stationId\"] == \"1166579522\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Weather Stations",
   "type": "table",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"sis\")\n  |> range(start: -1y)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"device_registration\")\n  |> filter(fn: (r) => r[\"_field\"]==\"stationName\")\n  |> group(columns: [\"stationName\"])\n  |> keep(columns: [\"stationId\", \"_value\"])\n  |> rename(columns: {\"stationId\": \"Id\", _value: \"Name\"})\n",
     "type": "table"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "short", "label": "Temperature (C)" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"test\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TestWeatherStation\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temp\") ",
     "type": "timeseries"
    }
   ]
  },
  {
   "title": "Average Temperatures (past 24h)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"flwsb\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weather_station\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temp\")\n  |> aggregateWindow(every: 1d, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "type": "gauge"
    }
   ]
  },
  {
   "title": "Rain",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "yaxes": [
    { "format": "short", "label": "Rain (mm)" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"flwsb\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weather_station\")\n  |> filter(fn: (r) => r[\"_field\"] == \"rain\")",
     "type": "timeseries"
    }
   ]
  },
  {
   "title": "Average Rainfall (past 24h)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "query": "from(bucket: \"flwsb\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weather_station\")\n  |> filter(fn: (r) => r[\"_field\"] == \"rain\")\n  |> aggregateWindow(every: 1d, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "type": "gauge"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "yaxes": [
    { "format": "short", "label": "Humidity (%)" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"flwsb\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weather_station\")\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")",
     "type": "timeseries"
    }
   ]
  },
  {
   "title": "Average Humidity (past 24h)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"flwsb\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weather_station\")\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\n  |> aggregateWindow(every: 1d, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "type": "gauge"
    }
   ]
  },
  {
   "title": "Wind Direction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "yaxes": [
    { "format": "short", "label": "Wind Direction (degrees)" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"flwsb\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weather_station\")\n  |> filter(fn: (r) => r[\"_field\"] == \"wind_direction\")",
     "type": "timeseries"
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "yaxes": [
    { "format": "short", "label": "Wind Speed (m/s)" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"test\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weather_station\")\n  |> filter(fn: (r) => r[\"_field\"] == \"wind_speed\")",
     "type": "timeseries"
    }
   ]
  },
  {
   "title": "Wind Gust",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "yaxes": [
    { "format": "short", "label": "Wind Gust (m/s)" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"flwsb\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weather_station\")\n  |> filter(fn: (r) => r[\"_field\"] == \"wind_gust\")",
     "type": "timeseries"
    }
   ]
  }
 ]
}